#!/bin/bash

SHELFPLAY_PORT=1337

alias shelfdisplay="export DISPLAY=\"shelf:0\""
alias shelfnodisplay="export DISPLAY=\"0:0\""

function shelfkvm {
	x2vnc shelf:0 -edgewidth 0
}

function shelfweb {
	ssh shelf@shelf "export DISPLAY=\"0:0\"; chromium $1"
}

function shelfmsg {
	ssh shelf@shelf "export DISPLAY=\"0:0\"; zenity --info --text \"$1\""
}

function shelfalsa {
	ssh shelf@shelf -t "alsamixer"
}

function shelfoff {
	ssh shelf@shelf "export DISPLAY=\"0:0\"; xset dpms force off"
}

function shelfon {
	ssh shelf@shelf "export DISPLAY=\"0:0\"; xset dpms force on"
}

function shelfeject {
	ssh shelf@shelf "eject -T"
}

function shelfmstop {
	ssh shelf@shelf "mpc stop"
}

function shelfmplay {
	ssh shelf@shelf "mpc play"
}

function shelfdvd {
	ssh shelf@shelf "mpc stop; export DISPLAY=\"0:0\"; vlc dvd:// -f"
}
